import logging
import time
from orchestration.orchestrator.registry import registry, AgentCapabilities
from orchestration import InputData, AgentResponse, ResponseStatus
from orchestration.orchestrator.config import key_manager
from orchestration.orchestrator.llm import call_gemini
from orchestration.orchestrator.schemas.planning import ReviewDecision

logger = logging.getLogger(__name__)

@registry.register("reviewer", AgentCapabilities(description="Reviews generated content and code.", tools=[], agent_level="MANAGER"))
def reviewer_agent(task_data: InputData) -> AgentResponse:
    logger.info("Routing to Reviewer Agent")
    start_time = time.time()
    
    my_key = key_manager.get_api_key_for_role("REVIEWER")
    # System instruction tailored for this agent
    sys_prompt = """You are the Reviewer Manager in an Agentic AI system.
You will be provided with the original user request and the final output generated by the worker agents.
Your job is to review the output and decide if it satisfies the original request.
You MUST output ONLY a valid JSON object with the following schema:
{
  "status": "approved" | "rejected",
  "feedback": "detailed explanation of why it was approved or rejected"
}"""
    
    # Call the GenAI LLM
    content = call_gemini(
        prompt=task_data.text_content, 
        api_key=my_key, 
        system_instruction=sys_prompt, 
        agent_id="reviewer", response_schema=ReviewDecision
    )
    execution_time = (time.time() - start_time) * 1000
    
    return AgentResponse(
        agent_id="reviewer",
        status=ResponseStatus.SUCCESS,
        content=content,
        tool_calls=[],
        execution_time_ms=execution_time,
        metadata={"processed_modality": task_data.input_type.value}
    )
